name: "Build Packages"
on:
  workflow_dispatch: {}

jobs:
  build_packages:
    continue-on-error: true
    strategy:
      matrix:
        package:
        - kernel_linux_6_1_rockchip
        - uBootKing3399
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        DEBIAN_FRONTEND=noninteractive
        sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    - uses: cachix/cachix-action@v12
      with:
        name: nabam-nixos-rockchip
        authToken: '${{ secrets.CACHIX_TOKEN }}'
    - run: |
        nix build -L -j4 .#${{ matrix.package }}
